services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: composer install && php artisan key:generate && php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_KEY
        value: your-app-key
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: your-db-port
      - key: DB_DATABASE
        value: your-db-database
      - key: DB_USERNAME
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password
    publish:
      path: public
